apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/kube-prometheus-stack/versions/kube-prometheus-stack-88.3.0

patches:
  - path: values-dev.yaml
    target:
      kind: Application
      name: kube-prometheus-stack