apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: kube-prometheus-stack
spec:
  project: dev
  source:
    repoURL: git@github.com:Prathama-sanshi/Argocd-and-Observability.git
    targetRevision: gitops-obs
    path: Application/helm-charts/kube-prometheus-stack/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true