apiVersion: v1
kind: Secret
metadata:
  name: argocd-git
  namespace: argocd
  labels:
    # This line tells Argo CD to treat this Secret as a Repository
    argocd.argoproj.io/secret-type: repository
    # CRITICAL: This line locks the repository to the "dev" project
    argocd.argoproj.io/project: "dev"
type: Opaque
stringData:
  type: git
  url: <YOUR GIT REPO URL>
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    <YOUR PRIVATE KEY>
    -----END OPENSSH PRIVATE KEY-----
