apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
helmGlobals:
  chartHome: ../../../../../helm-charts/file-monitor-charts 

helmCharts:
  - name: file-monitor-0.1.0
    releaseName: file-monitor
    namespace: dev
    valuesFile: values.yaml