apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp-credentials
  namespace: observability
type: Opaque
stringData:
  # ⚠️ Use your generated 16-character Mail App Password here
  password: "dalgtpmowzitvlis" 
