apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: file-monitor
    release: observability 
  name: custom-file-monitor-podmonitor
  namespace: default
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: file-monitor