apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-monitor
  namespace: argocd
  labels:
    app: file-monitor
spec:
  project: default
  source:
    repoURL: https://github.com/Prathama-sanshi/Argocd-and-Observability.git
    targetRevision: gitops-obs
    path: Application/helm charts/file-monitor-charts
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
