apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-monitor
  namespace: argocd 
spec:
  project: dev
  source:
    repoURL: git@github.com:Prathama-sanshi/Argocd-and-Observability.git
    targetRevision: gitops-obs
    path: ../apps/overlays/dev-cluster/dev-file-monitor/dev-app
    plugin:
      name: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
