name: FluxCD Setup 

# Trigger the workflow only on changes to the main branch
on:
  workflow_dispatch: # Enables the manual trigger button



jobs:
  sanity-check:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: "${{ github.workspace }}"

    steps:
      - name: pre-check
        shell: bash
        run: |
         flux --version     #flux version 2.9.5 or above
         docker --version   #Docker version 29.3.0 or above
         minikube version   #minikube version: v1.38.0 or above
         minikube start

  deploy-flux:
    needs: sanity-check
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: "${{ github.workspace }}"
    
    steps:
      - name: Checkout Specific Branch
        uses: actions/checkout@v4
        with:
          ref: fluxcd-obs 
      - name: helm install fluxcd
        run: |
          echo "Installing FluxCD..."
          pwd
          cd FluxCD/Helm-chart/flux2/
          echo "Patching existing Flux CRDs to allow Helm adoption..."
          # 1. Get all CRDs containing 'fluxcd.io'
          # 2. Add the tracking label Helm requires
          # 3. Add the tracking annotations Helm requires
          for crd in $(kubectl get crd -o jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep 'fluxcd.io'); do
              echo "Adopting CRD: $crd"
              kubectl label crd "$crd" app.kubernetes.io/managed-by=Helm --overwrite
              kubectl annotate crd "$crd" meta.helm.sh/release-name=fluxcd meta.helm.sh/release-namespace=flux-system --overwrite
          done

          helm upgrade --install fluxcd . \
            -f values.yaml \
            -n flux-system \
            --create-namespace \
            --force

          cd ../../Resources
          pwd
          flux install --force #install crd
          kubectl apply -f GitRepository.yaml
          kubectl delete secret git-credentials -n flux-system --ignore-not-found=true
          kubectl create secret generic git-credentials -n flux-system --from-literal=username=oauth2 --from-literal=password=${{ secrets.GITHUB_TOKEN }}
          kubectl apply -f kustomization.yaml
          echo "FluxCD setup completed!"
