name: FluxCD - Gitops Undeployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      undeploy_file_monitor:
        description: 'Undeploy File monitoring application'
        type: boolean
        default: true
      undeploy_observability:
        description: 'Undeploy observability'
        type: boolean
        default: true

jobs:
  undeploy-apps:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout Specific Branch
        uses: actions/checkout@v4
        with:
          ref: fluxcd-obs 
    
      - name: Undeploy apps
        run: | 
          git config --global user.email "psanshi@example.com"
          git config --global user.name "psanshi"
          cd Application/apps/overlays/dev-cluster/
          cat kustomization.yaml
          if ${{ inputs.undeploy_file_monitor }} == "true" and ${{ inputs.undeploy_observability }} == "true" ; then
            echo "Undeploying file monitor"
            sed -i 's/#*[[:space:]]*resources:/#resources:/' kustomization.yaml
            sed -i 's/  - dev-file-monitor/#  - dev-file-monitor/' kustomization.yaml
            sed -i 's/  - dev-kube-prometheus-stack/#  - dev-kube-prometheus-stack/' kustomization.yaml
          fi

          if ${{ inputs.undeploy_file_monitor }} == "true" and ${{ inputs.undeploy_observability }} == "false" ; then
            echo "Undeploying file monitor"
            sed -i 's/  - dev-file-monitor/#  - dev-file-monitor/' kustomization.yaml
            if grep -rnE "^\s*#\s*- dev-kube-prometheus-stack" . ; then
              sed -i 's/#*[[:space:]]*resources:/#resources:/' kustomization.yaml
            fi
          fi
          if ${{ inputs.undeploy_observability }} == "true" and ${{ inputs.undeploy_file_monitor }} == "false"; then
            echo "Undeploying observability"
            sed -i 's/  - dev-kube-prometheus-stack/#  - dev-kube-prometheus-stack/' kustomization.yaml
            if grep -rnE "^\s*#\s*- dev-file-monitor" . ; then
              sed -i 's/#*[[:space:]]*resources:/#resources:/' kustomization.yaml
            fi
          fi
          cat kustomization.yaml
          #commit and push the changes
          git add kustomization.yaml
          git commit -m "Undeploy Apps $(date)"
          echo "Changes committed successfully : msg - $(git log --oneline -1)"
          git push origin HEAD:fluxcd-obs
          echo "push successful"
