name: Uninstall Flux - cleanup

on:
  workflow_dispatch: # Enables the manual trigger button



jobs:
  flux-uninstall:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: "${{ github.workspace }}"

    steps:
      - name: flux-clean-up
        shell: bash
        run: |
          minikube start
          helm uninstall fluxcd -n flux-system
          flux delete source git fluxcd-obs -n flux-system --silent
          flux delete kustomization fluxcd-obs -n flux-system --silent
          kubectl get namespace flux-system -o json | tr -d "\n" | sed "s/\"finalizers\": \[[^]]*\]/\"finalizers\": []/" | kubectl replace --raw /api/v1/namespaces/flux-system/finalize -f -
          minikube stop
         


